# Generated by Django 5.1.3 on 2024-11-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='home_blog_slug_e4fe6c_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['created_at'], name='home_blog_created_8aead1_idx'),
        ),
    ]
